# Generated by Django 3.1.7 on 2021-04-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='flies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attachment', models.FileField(blank=True, upload_to='media')),
            ],
        ),
        migrations.DeleteModel(
            name='Uploads',
        ),
    ]
