# Generated by Django 3.1.7 on 2021-04-05 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEB_APP', '0002_auto_20210405_1440'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='flies',
            new_name='files',
        ),
    ]
