# Generated by Django 3.1.7 on 2021-04-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB_APP', '0003_auto_20210405_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='attachment',
            field=models.FileField(blank=True, upload_to='pdf/'),
        ),
    ]
